### PR TITLE
Expose number of errors in Result

### PR DESCRIPTION
**Pull request by rvansa**

### CODE REVIEW

**Comment by whitingjr** [comment]
Please add comments to the methods in the concrete class. Just as all the existing methods do.

**Comment by rvansa** [comment]
@whitingjr Ok, though I was wondering why there is such practice... Drivers should always use only the interface, not implementation.

**Comment by whitingjr** [comment]
Trying to keep the code-base consistent.

**Comment by rvansa** [comment]
@whitingjr updated.

**Comment by whitingjr** [comment]
thank you.

**Pull request merged**
